#!/system/bin/sh	

mount -o remount,rw /cache
mkdir -p /cache/dalvik-cache
chmod 777 /cache/dalvik-cache

less /data/system/extinternal | grep -q 1 || exit

sleep 3
mount -o remount,rw /
mount -t vfat -o umask=0000 /dev/block/vold/179:97 /mnt/shell/emulated
mount -o bind /data/media/0 /storage/sdcard1
chown system /data/media/0
chgrp sdcard_rw /data/media/0
chmod 0075 /data/media/0
mount -o remount, ro /
